<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="MostrarPortatilesconGridyDetailsView.aspx.cs" Inherits="WebNCapas.MostrarPortatilesconGridyDetailsView" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
         Productos usando Grid View y Details View <br />
        <asp:ObjectDataSource ID="ObjectDataSource1" runat="server" SelectMethod="GetProductos" TypeName="WebNCapas.BLL.ProductoMgr"></asp:ObjectDataSource>
        <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" DataSourceID="ObjectDataSource1" DataKeyNames="ID" >
            <Columns>
                <asp:CommandField ShowSelectButton="True" />
                <asp:BoundField DataField="ID" HeaderText="ID" SortExpression="ID" />
                <asp:BoundField DataField="Nombre" HeaderText="Nombre" SortExpression="Nombre" />
                <asp:BoundField DataField="Detalles" HeaderText="Detalles" SortExpression="Detalles" />
                <asp:BoundField DataField="Precio" HeaderText="Precio" SortExpression="Precio" />
                <asp:BoundField DataField="Foto" HeaderText="Foto" SortExpression="Foto" />
                

            </Columns>
         </asp:GridView>



        <asp:ObjectDataSource ID="ObjectDataSource2" runat="server" SelectMethod="GetProducto"  TypeName="WebNCapas.BLL.ProductoMgr">
         
            <SelectParameters>
                <asp:ControlParameter ControlID="GridView1" Name="pID" PropertyName="SelectedValue" />
            </SelectParameters>
              
        </asp:ObjectDataSource>
     
        <asp:DetailsView ID="DetailsView1" runat="server" Height="50px" Width="125px" DataSourceID="ObjectDataSource2"
            AutoGenerateEditButton="true" AutoGenerateInsertButton="true" AutoGenerateDeleteButton="true"></asp:DetailsView>

    </form>
</body>
</html>
